version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    restart: always

  my_app:
    build: .
    depends_on:
      - selenium
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: python3 -u main.py >> /home/ubuntu/scripts/output.log 2>&1
    restart: always
